Wafoods/Wafoods/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/',include('reservation.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('qee/', include("qee.urls")),
    path('', include('washoku.urls')),

]

Wafoods/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
]

Wafoods/qee/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'post/',views.post,name="post"),
    url(r'',views.index,name="index"),
    
]

Wafoods/reservation/urls.py
from django.urls import path
from reservation import views
from django.conf.urls import url

app_name="reservation"
urlpatterns = [
    url(r'confirmation/([0-9]+)',views.confirm,name='confirm'),
    url(r'my_reserve/delete/([0-9]+)/$',views.reserve_delete,name='reserve_delete'),
    url(r'my_reserve',views.my_reserve,name='my_reserve'),
    url(r'([0-9]+)',views.reserve,name='reserve'),
]

Wafoods/washoku/urls.py
from django.urls import path
from django.conf.urls import url
from washoku import views
from washoku.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
)

app_name = 'washoku'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),

    
    path('create_restaurant/', views.create_restaurant, name='create_restaurant'),
    url(r'restaurant/([0-9]+)/',views.restaurantview,name='restaurant'),
    url(r'restaurant_en/([0-9]+)/',views.restaurantview_en,name='restaurant_en'),
    url(r'restaurant_list/delete/([0-9]+)',views.restaurant_delete,name='restaurant_delete'),
    url(r'restaurant_list/',views.RestaurantListView.as_view(),name='restaurant_list'),
    url(r'reserve_list/([0-9]+)',views.reserve_list,name="reserve_list"),
    
    url(r'calc_menu_en/([0-9]+)',views.calc_menu_en,name='calc_menu_en'),
    url(r'calc_menu/([0-9]+)',views.calc_menu,name='calc_menu'),
    

    url(r'make_menu/([0-9]+)',views.make_menu,name='make_menu'),
    url(r'menu/([0-9]+)/delete/',views.menu_delete,name='menu_delete'), 
    url(r'menu_en/([0-9]+)',views.menu_en,name='menu_en'),  
    url(r'menu/([0-9]+)',views.menu,name='menu'), 
    
    url(r'make_course/([0-9]+)',views.make_course,name='make_course'),
    url(r'course/([0-9]+)/delete/',views.course_delete,name='course_delete'),
    url(r'course_en/([0-9]+)',views.course_en,name='course_en'),  
    url(r'course/([0-9]+)',views.course,name='course'), 


    
    

]

Wafoods/templates/base/navbar.html
<div id="header">
    <header class="site-header">
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li><a class="navbar-brand" href="/">top</a ></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">

                <ul class="menu">
                    <li class="menu__single">
                        <a href="#" class="init-bottom">MyPage</a>
                        <ul class="menu__second-level">
                            <li><a class="dropdown-item" href="{% url 'accounts:user_detail' user.pk %}">Plofile</a></li>
                        <li><a class="dropdown-item" href="{% url 'reservation:my_reserve' %}">My Rservation List</a></li>
                        <li><a class="dropdown-item" href="{% url 'washoku:restaurant_list' %}">My Restaurant List</a></li>
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item" href="{% url 'accounts:user_update' user.pk %}">Update user information</a></li>
                        </ul>
                    </li>
                    <!-- 他グローバルナビメニュー省略 -->
                </ul>
                </li>

                <li>
                    <a class="nav-item nav-link" href="{% url 'washoku:create_restaurant' %}">店舗作成</a>    
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">
                        Login
                    </a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                {% endif %}
                <li>{% include "washoku/snippets/search_form.html" %}</li>
            </ul>
        </div>
    
    </div>
</nav>

</header>
</div>

Wafoods/templates/base/pagination.html
<div>
  <nav aria-label="Page navigation example" class="aaa">
      <ul class="pagination">
          {% if page_obj.has_previous %}
              <li class="page-item><a class="page-link text-primary d-inline-block" href="?page={{ page_obj.previous_page_number }}">前</a></li>
          {% else %}
              <li class="disabled page-item"><div class="page-link text-secondary d-inline-block ddd" href="#">前</div></li>
          {% endif %}

          {% for link_page in page_obj.paginator.page_range %}
              {% if link_page %}
                  {% if link_page == page_obj.number %}
                      <li class="disabled page-item"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ link_page }}</div></li>
                  {% else %}
                      <li class="page-item"><a class="page-link text-primary d-inline-block ddd" href="?page={{ link_page }}">{{ link_page }}</a></li>
                  {% endif %}
              {% else %}
                  <li class="disabled page-item"><a class="page-link text-secondary d-inline-block text-muted ddd" href="#">・・・</a></li>
              {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link text-primary d-inline-block ddd" href="?page={{ page_obj.next_page_number }}">次</a></li>
          {% else %}
              <li class="disabled page-item"><div class="page-link text-secondary d-inline-block disabled ddd" href="#">次</div></li>
          {% endif %}
      </ul>
  </nav>
</div>