Wafoods/Wafoods/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/',include('reservation.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('qee/', include("qee.urls")),
    path('', include('washoku.urls')),

]

Wafoods/qee/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'post/',views.post,name="post"),
    url(r'',views.index,name="index"),
    
]

Wafoods/reservation/urls.py
from django.urls import path
from reservation import views
from django.conf.urls import url

app_name="reservation"
urlpatterns = [
    url(r'confirmation/([0-9]+)',views.confirm,name='confirm'),
    url(r'my_reserve/delete/([0-9]+)/$',views.reserve_delete,name='reserve_delete'),
    url(r'my_reserve',views.my_reserve,name='my_reserve'),
    url(r'([0-9]+)',views.reserve,name='reserve'),
]

Wafoods/washoku/urls.py
from django.urls import path
from django.conf.urls import url
from washoku import views
from washoku.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
)

app_name = 'washoku'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),

    
    path('create_restaurant/', views.create_restaurant, name='create_restaurant'),
    url(r'restaurant/([0-9]+)/',views.restaurantview,name='restaurant'),
    url(r'restaurant_en/([0-9]+)/',views.restaurantview_en,name='restaurant_en'),
    url(r'restaurant_list/delete/([0-9]+)',views.restaurant_delete,name='restaurant_delete'),
    url(r'restaurant_list/',views.RestaurantListView.as_view(),name='restaurant_list'),
    url(r'reserve_list/([0-9]+)',views.reserve_list,name="reserve_list"),
    
    url(r'calc_menu_en/([0-9]+)',views.calc_menu_en,name='calc_menu_en'),
    url(r'calc_menu/([0-9]+)',views.calc_menu,name='calc_menu'),
    

    url(r'make_menu/([0-9]+)',views.make_menu,name='make_menu'),
    url(r'menu/([0-9]+)/delete/',views.menu_delete,name='menu_delete'), 
    url(r'menu_en/([0-9]+)',views.menu_en,name='menu_en'),  
    url(r'menu/([0-9]+)',views.menu,name='menu'), 
    
    url(r'make_course/([0-9]+)',views.make_course,name='make_course'),
    url(r'course/([0-9]+)/delete/',views.course_delete,name='course_delete'),
    url(r'course_en/([0-9]+)',views.course_en,name='course_en'),  
    url(r'course/([0-9]+)',views.course,name='course'), 


    
    

]

Wafoods/washoku/forms.py
from django.forms import ModelForm, TextInput, Textarea

from django import forms

from washoku.models import Comment, Reply, Restaurant, Menu, Course

from cloudinary.forms import CloudinaryFileField #追加


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'コメント内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

class PhotoForm(forms.Form):
    image = forms.ImageField()

class RestaurantForm(forms.Form):
    name=forms.CharField()
    address=forms.CharField()
    detail=forms.CharField(widget=forms.Textarea)
    image = CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'Restaurant'})

class MenuForm(forms.Form):
    name=forms.CharField(label="メニュー名")
    price=forms.IntegerField(label="料金(税込)")
    description=forms.CharField(label="料理の説明",widget=forms.Textarea)
    image=CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'Menu'})

class CourseForm(forms.Form):
    name=forms.CharField(label="コース名")
    number_of_menus=forms.IntegerField(label="品目数")
    number_of_people=forms.CharField(label="人数")
    price=forms.IntegerField(label="料金(税込)")
    menus=forms.CharField(label="メニュー",widget=forms.Textarea)
    image = CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'course'})

Wafoods/washoku/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from washoku.forms import CommentForm, ReplyForm, RestaurantForm, CourseForm, MenuForm
from washoku.models import Post, Category, Tag, Comment, Reply, Restaurant, Menu, Course
from reservation.models import Reserve

from googletrans import Translator


from PIL import Image
# Create your views here.

class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Restaurant
    template_name = 'washoku/index.html'
    paginate_by = 3


class CategoryPostView(ListView):
    model = Post
    template_name = 'washoku/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'washoku/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'washoku/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('washoku:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('washoku:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('washoku:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('washoku:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('washoku:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('washoku:post_detail', pk=reply.comment.post.pk)


#########

class MenuCourseListView(ListView):
    model = Menu
    context_object_name='menu'
    template_name='washoku/snippets/menu_course_list.html'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'courses' : Course.objects.all()
        })
        return context



def restaurantview(request,restaurant_id):
    if request.method == 'GET':
        return render(request, 'washoku/restaurant.html', {
            'menu' : Menu.objects.all(),
            'courses' : Course.objects.all(),
            'restaurant' : Restaurant.objects.get(pk=restaurant_id),
        })

def restaurantview_en(request,restaurant_id):
    if request.method == 'GET':
        return render(request, 'washoku/restaurant_en.html', {
            'menu' : Menu.objects.all(),
            'courses' : Course.objects.all(),
            'restaurant' : Restaurant.objects.get(pk=restaurant_id),
        })

def create_restaurant(request):
    if request.method=="GET":
        form=RestaurantForm()
        return render(request, 'washoku/create_restaurant.html', {'form':form})
    elif request.method=="POST":
        form = RestaurantForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()

        sent_detail_en=trans.translate(form.cleaned_data['detail'],dest="en").text

        restaurant = Restaurant()
        restaurant.name = form.cleaned_data['name']
        restaurant.address = form.cleaned_data['address']
        restaurant.detail = form.cleaned_data['detail']
        restaurant.detail_en = sent_detail_en
        restaurant.owner_id = request.user.id

        restaurant.image = form.cleaned_data['image']

        restaurant.save()
        return redirect("restaurant/"+str(restaurant.id))
    return render(request,'washoku/create_restaurant.html')

def restaurant_delete(request,rest_id):
    restaurant = Restaurant.objects.get(pk=rest_id)
    restaurant.delete()
    return redirect('/')


from .forms import PhotoForm
from .models import Photo


def photo(req):
    if req.method == 'GET':
        return render(req, 'washoku/create_restaurant.html', {
            'form': PhotoForm(),
            'photos': Photo.objects.all(),
        })

    elif req.method == 'POST':                                                     
        form = PhotoForm(req.POST, req.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        photo = Photo()
        photo.image = form.cleaned_data['image']
        photo.save()

        return redirect('/')

def make_menu(request,rest_id):
    
    if request.method == 'GET':
        form=MenuForm()
        return render(request, 'washoku/make_menu.html', {'form':form})

    if request.method=="POST":
        form = MenuForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()

        sent_name_en=trans.translate(form.cleaned_data['name'],dest="en").text
        sent_description_en=trans.translate(form.cleaned_data['description'],dest="en").text

        menu=Menu()
        menu.name=form.cleaned_data['name']
        menu.name_en=sent_name_en
        menu.price=form.cleaned_data['price']
        menu.description=form.cleaned_data['description']
        menu.description_en=sent_description_en
        menu.restaurant_id=rest_id

        menu.image = form.cleaned_data['image'] 
        menu.save()
        return redirect('restaurant/'+str(rest_id))

def menu(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    data={"menu":menu}
    return render(request,'washoku/menu.html',data)

def menu_en(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    data={"menu":menu}
    return render(request,'washoku/menu_en.html',data)

def menu_delete(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    rest_id=menu.restaurant_id
    menu.delete()
    return redirect('/restaurant/'+str(rest_id))


def make_course(request,rest_id):
    if request.method == 'GET':
        form=CourseForm()
        return render(request, 'washoku/make_course.html', {'form':form})

    elif request.method == 'POST':                                                     
        form = CourseForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()
        sent_name_en=trans.translate(form.cleaned_data['name'],dest="en").text
        sent_menus_en=trans.translate(form.cleaned_data['menus'],dest="en").text
        

        course = Course()
        course.name=form.cleaned_data['name']
        course.name_en=sent_name_en
        course.number_of_menus=form.cleaned_data['number_of_menus']
        course.number_of_people=form.cleaned_data['number_of_people']
        course.price=form.cleaned_data['price']
        course.menus=form.cleaned_data['menus']

Wafoods/washoku/templates/washoku/calc_menu.html
{% extends "base.html" %}

{% block title %}料金計算 | {{ block.super }}{% endblock %}
{% block description %}料金計算{% endblock %}

{% block content %}
<h1 id="ww">料金計算</h1>
{% load cloudinary %}
<form name="menu">
                <table>
                    {% for m in menu %}
                    {% if restaurant.id == m.restaurant_id %}
                    <tr>
                        <td>
                            <a href="{% url 'washoku:menu' m.id %}">
                                    {% cloudinary m.image.url width=100 height=100 %}
                                {{ m.name }}
                            </a>
                        </td>
                        <td>
                            <span name="price">{{ m.price }}</span>円
                        </td>
                        <td>
                            <input type="number" name="menu2">
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </table>
                </form>

    <p>
        <input type="button" value="合計" onclick="clickbtn()">
    </p>
    
    <p><span id="total"></span></p>
    
    <script>
            function clickbtn(){
                var num = document.menu.menu2
                var total=0;

                for (let i = 0; i < num.length; i++){
                    var price=document.getElementsByName("price");
                    total += Number(price[i].innerHTML)*num[i].value;
                    
                }
                document.getElementById("total").innerHTML=total+"円";
            }
        </script>

{% endblock %}

Wafoods/washoku/templates/washoku/calc_menu_en.html
{% extends "base.html" %}

{% block title %}料金計算 | {{ block.super }}{% endblock %}
{% block description %}料金計算{% endblock %}

{% block content %}
<h1 id="ww">料金計算</h1>
<form name="menu">
        {% load cloudinary %}
    <table>
    {% for m in menu %}
    {% if restaurant.id == m.restaurant_id %}
             <tr>
                <td>
                    <a href="{% url 'washoku:menu' m.id %}">
                        {% cloudinary m.image.url width=100 height=100 %}
                        {{ m.name_en }}
                    </a>
                </td>
                <td>
                    ¥<span name="price">{{ m.price }}</span>
                </td>
                        <td>
                            <input type="number" name="menu2">
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </table>
                </form>

    <p><span id="total"></span></p>
    <input type="button" value="合計" onclick="clickbtn()">
    
    
    <script>
            function clickbtn(){
                var num = document.menu.menu2
                var total=0;

                for (let i = 0; i < num.length; i++){
                    var price=document.getElementsByName("price");
                    total += Number(price[i].innerHTML)*num[i].value;
                    
                }
                document.getElementById("total").innerHTML=total+"円";
            }
        </script>

{% endblock %}

Wafoods/washoku/templates/washoku/category_post.html
{% extends "base.html" %}

{% block title %}{{ category.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ category.name }}」の投稿一覧ページです。{% endblock %}

{% block content %}
<h1 id="ww">投稿一覧</h1>
<div class="container">
    <div class="row">
        <main class="col-md-8">
            <h1 class="mb-4">「{{ category.name }}」の投稿一覧</h1>
            {% include "washoku/snippets/main_post_list.html" %}
        </main>
        <aside class="col-md-4">
            {% include "washoku/snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock %}

Wafoods/washoku/templates/washoku/course_en.html
{% extends "base.html" %}

{% block title %}Course | {{ block.super }}{% endblock %}
{% block description %}Course{% endblock %}

{% block content %}

        <h1>{{ course.name_en }}</h1>
        {% load cloudinary %}
        <a href="{% url 'washoku:restaurant_en' course.restaurant_id %}">back</a>
        <br>
        <p class="resizeimage">
        {% cloudinary course.image.url width=600 height=400 %}
        </p>
        <table>
                <tr>
                    <td>{{ course.name_en }}</td>
                </tr>
                <tr>
                    <td>¥{{ course.price }}</td>
                </tr>
                <tr>
                    <td>{{ course.number_of_menus }} dishes</td>
                </tr>
                <tr>
                    <td>
                        {% if course.number_of_people == 1 %}
                        1 parson
                        {% else %}
                        {{ course.number_of_people }} people
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>{{ course.menus_en }}</td>
                </tr>
            </table>
        <p>
            <a href="{% url 'washoku:course' course.id %}">日本語版.</a>
        </p>
{% endblock %}

Wafoods/washoku/templates/washoku/create_restaurant.html
{% extends "base.html" %}

{% block title %}店舗作成 | {{ block.super }}{% endblock %}
{% block description %}作成用{% endblock %}

{% block content %}
{% load static %}
<h1 id="ww">店舗作成</h1>
    <table>
        <form action="{% url 'washoku:create_restaurant' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_table }}
            <tr><td><a class="zzz"></a><input id="btn" type="submit" value="作成"></a></td></tr>
        </form>        
    </table>
{% endblock %}

<!--<a class="xxx">{{ form.as_table }}</a>
            <a class="zzz"></a><input id="btn" type="submit" value="作成"></a>-->

Wafoods/washoku/templates/washoku/index.html
{% extends "base.html" %}


{% block title %}店舗一覧 | {{ block.super }}{% endblock %}
{% block description %}和食店{% endblock %}

{% block content %}
{% load static %}


<div class="container">
    <div class="row">
        <main class="col-md-8">
            <h1 class="mb-4" id="ww">店舗一覧</h1>
            {% load cloudinary %}
            <!--
    {% include "washoku/snippets/main_post_list.html" %}
    -->
            <table>
            {% for r in object_list %}
        <tr>
            
            <td>
                <a href="{% url 'washoku:restaurant' r.id %}">
                {% cloudinary r.image.url width=100 height=100 %}
                {{ r.name }}
            </a>
            </td>
            <td>
                {% if request.user.id == r.owner_id %}
                <a href="">削除</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    
    
            {% include "washoku/snippets/pagination.html" %}
        </main>
        <aside class="col-md-4">
            {% include "washoku/snippets/sidebar.html" %}
        </aside>
    </div>
</div>

{% endblock %}

Wafoods/washoku/templates/washoku/make_course.html
{% extends "base.html" %}

{% block title %}コース作成 | {{ block.super }}{% endblock %}
{% block description %}コース作成{% endblock %}

{% block content %}
        <h1 id="ww">コース作成</h1>
        <table>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_table }}
                <tr>
                    <td>
                        <a class="zzz"><input id="btn" type="submit" value="作成"></a>
                    </td>
                </tr>
            </form>
        </table>
{% endblock %}

Wafoods/washoku/templates/washoku/make_menu.html
{% extends "base.html" %}

{% block title %}メニュー作成 | {{ block.super }}{% endblock %}
{% block description %}メニュー作成{% endblock %}

{% block content %}
        <h1 id="ww">メニュー作成</h1>
        <table>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td>
                    <a class="zzz"><input id="btn" type="submit" value="作成"></a>
                </td>
            </tr>
        </form>
    </table>
{% endblock %}

Wafoods/washoku/templates/washoku/menu.html
{% extends "base.html" %}

{% block title %}メニュー | {{ block.super }}{% endblock %}
{% block description %}メニュー{% endblock %}

{% block content %}
        <h1 id="ww">{{ menu.name }}</h1>
        {% load cloudinary %}
        <a href="{% url 'washoku:restaurant' menu.restaurant_id %}">戻る</a>
        <br>
        <p class="resizeimage">
        {% cloudinary menu.image.url width=600 height=400 %}
        </p>
        <br>
        menu:{{ menu.name }}
        ({{ menu.price }}円)
        <br>
        description:{{ menu.description }}
        <p>
            <a href="{% url 'washoku:menu_en' menu.id %}">english ver.</a>
        </p>
{% endblock %}

Wafoods/washoku/templates/washoku/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }} | {{ block.super }}{% endblock %}
{% block description %}{{ object.description }}{% endblock %}

{% block content %}
<h1 id="ww">コメントの投稿</h1>
<div class="container">
    <div class="row">
        <main class="col-md-8">
            <article class="blog-area">
                <h1>{{ object.title }}</h1>
                <p>{{ object.published_at|date }}</p>
                <p>{{ object.category.name }}</p>
                {% for tag in object.tags.all %}
                {{ tag.name }}
                {% endfor %}
                <hr>
                {{ object.content|safe }}
            </article>
            <article class="comment-area">
                <a class="btn btn-primary my-3" href="{% url 'washoku:comment_form' post.pk %}">コメントを投稿する</a>
                {% include "washoku/snippets/comments.html" %}
            </article>
        </main>

        <aside class="col-md-4">
            {% include "washoku/snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock %}

Wafoods/washoku/templates/washoku/restaurant.html
{% extends "base.html" %}

{% block title %}店舗詳細 | {{ block.super }}{% endblock %}
{% block description %}店舗詳細{% endblock %}

{% block content %}
<h1 id="ww">{{ restaurant.name }}</h1>
{% load cloudinary %}
<a href="{% url 'washoku:restaurant_en' restaurant.id %}">English var.</a>
<button><a class="zzz" href="{% url 'reservation:reserve' restaurant.id %}">予約</a></button>
{% if request.user.id == restaurant.owner_id %}
<a href="{% url 'washoku:reserve_list' restaurant.id %}">予約確認</a>
{% endif %}
<p class="resizeimage">
{% cloudinary restaurant.image.url weight=600 height=400 %}
</p>
<br>
{{ restaurant.address }}
<br>
{{ restaurant.detail }}
<div>
    {% include 'washoku/snippets/menu_course_list.html' %}
</div>
    

{% endblock %}

Wafoods/washoku/templates/washoku/restaurant_list.html
{% extends "base.html" %}

{% block title %}店舗一覧 | {{ block.super }}{% endblock %}
{% block description %}和食店{% endblock %}

{% block content %}
<h1 id="ww">店舗一覧</h1>
<div class="container">
    <div class="row">
        <main class="col-md-8">
        
            {% load cloudinary %}
    <!--{% include "washoku/snippets/main_post_list.html" %}-->
    <table>
            {% for r in object_list %}
            {% if request.user.id == r.owner_id %}
        <tr>
            
            <td>
                <a href="{% url 'washoku:restaurant' r.id %}">
                    {% cloudinary r.image.url width=300 height=200 %}
                {{ r.name }}
            </a>
            </td>
            <td>
                {% if request.user.id == r.owner_id %}
                <a href="{% url 'washoku:restaurant_delete' r.id %}">削除</a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
    
    
            {% include "base/pagination.html" %}
        </main>
    </div>
</div>

{% endblock %}

Wafoods/washoku/templates/washoku/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <main class="col-md-8">
            <h1 class="mb-4">「{% if query %}{{ query }}{% endif %}」の検索結果</h1>
            <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
            {% include "washoku/snippets/main_post_list.html" %}
            {% include "washoku/snippets/pagination.html" %}
        </main>
        <aside class="col-md-4">
            {% include "washoku/snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock %}

Wafoods/washoku/templates/washoku/tag_post.html
{% extends "base.html" %}

{% block title %}#{{ tag.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ tag.name }}」の投稿一覧ページです。{% endblock %}

{% block content %}
<h1 id="ww">タグの投稿</h1>
<div class="container">
    <div class="row">
        <main class="col-md-8">
            <h1 class="mb-4">「#{{ tag.name }}」の投稿一覧</h1>
            {% include "washoku/snippets/main_post_list.html" %}
        </main>
        <aside class="col-md-4">
            {% include "washoku/snippets/sidebar.html" %}
        </aside>
    </div>
</div>
{% endblock %}