Wafoods/Wafoods/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/',include('reservation.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('qee/', include("qee.urls")),
    path('', include('washoku.urls')),

]

Wafoods/qee/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'post/',views.post,name="post"),
    url(r'',views.index,name="index"),
    
]

Wafoods/reservation/urls.py
from django.urls import path
from reservation import views
from django.conf.urls import url

app_name="reservation"
urlpatterns = [
    url(r'confirmation/([0-9]+)',views.confirm,name='confirm'),
    url(r'my_reserve/delete/([0-9]+)/$',views.reserve_delete,name='reserve_delete'),
    url(r'my_reserve',views.my_reserve,name='my_reserve'),
    url(r'([0-9]+)',views.reserve,name='reserve'),
]

Wafoods/washoku/urls.py
from django.urls import path
from django.conf.urls import url
from washoku import views
from washoku.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
)

app_name = 'washoku'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),

    
    path('create_restaurant/', views.create_restaurant, name='create_restaurant'),
    url(r'restaurant/([0-9]+)/',views.restaurantview,name='restaurant'),
    url(r'restaurant_en/([0-9]+)/',views.restaurantview_en,name='restaurant_en'),
    url(r'restaurant_list/delete/([0-9]+)',views.restaurant_delete,name='restaurant_delete'),
    url(r'restaurant_list/',views.RestaurantListView.as_view(),name='restaurant_list'),
    url(r'reserve_list/([0-9]+)',views.reserve_list,name="reserve_list"),
    
    url(r'calc_menu_en/([0-9]+)',views.calc_menu_en,name='calc_menu_en'),
    url(r'calc_menu/([0-9]+)',views.calc_menu,name='calc_menu'),
    

    url(r'make_menu/([0-9]+)',views.make_menu,name='make_menu'),
    url(r'menu/([0-9]+)/delete/',views.menu_delete,name='menu_delete'), 
    url(r'menu_en/([0-9]+)',views.menu_en,name='menu_en'),  
    url(r'menu/([0-9]+)',views.menu,name='menu'), 
    
    url(r'make_course/([0-9]+)',views.make_course,name='make_course'),
    url(r'course/([0-9]+)/delete/',views.course_delete,name='course_delete'),
    url(r'course_en/([0-9]+)',views.course_en,name='course_en'),  
    url(r'course/([0-9]+)',views.course,name='course'), 


    
    

]

Wafoods/reservation/models.py
from django.db import models

# Create your models here.

class Reserve(models.Model):
    name=models.CharField(max_length=256)
    datetime=models.DateTimeField()
    number_of_people=models.IntegerField()
    user_id=models.IntegerField()
    restaurant_id=models.IntegerField()
    def __str__(self):
        return self.name

Wafoods/reservation/forms.py
from django import forms
from .models import Reserve
from django.utils import timezone

class ReserveForm(forms.Form):
    name=forms.CharField()
    datetime = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local", "value": timezone.datetime.now().strftime('%Y-%m-%dT%H:%M')}),
        input_formats=['%Y-%m-%dT%H:%M'])
    number_of_people=forms.IntegerField()
    

Wafoods/reservation/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .forms import ReserveForm
from reservation.models import Reserve

# Create your views here.

def confirm(request,reserve_id):
    reservation = Reserve.objects.get(pk=reserve_id)
    data={"reservation":reservation}
    return render(request,'reservation/confirmation.html',data)

def reserve(request,rest_id):
    if request.method == 'GET':
        form=ReserveForm()
        return render(request,'reservation/reserve.html', {'form':form})

    elif request.method=="POST":
        form = ReserveForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        reserve=Reserve()
        reserve.name=form.cleaned_data['name']
        reserve.datetime=form.cleaned_data['datetime']
        reserve.number_of_people=form.cleaned_data['number_of_people']
        reserve.user_id=request.user.id
        reserve.restaurant_id=rest_id
        
        reserve.save()
        return redirect('confirmation/'+str(reserve.id))
    

@login_required
def reserve_delete(request,reserve_id):
    Reserve.objects.get(pk=reserve_id).delete()
    return redirect("my_reserve/")

@login_required
def my_reserve(request):
    """予約一覧"""
    reservation=Reserve.objects.all()
    return render(request,'reservation/my_reserve.html',{'reservation':reservation})

Wafoods/reservation/templates/reservation/confirmation.html
{% extends "base.html" %}

{% block title %}予約確認 | {{ block.super }}{% endblock %}
{% block description %}予約確認をするためのページです。{% endblock %}

{% block content %}
<h1 id="ww">予約確認</h1>
    名前:
    {{ reservation.name }}
    <br />
    日時:
    {{ reservation.datetime|date:"Y/m/j H:i" }}
    <br />
    人数:
    {{ reservation.number_of_people }}
    <br />
    ユーザーID:
    {{ reservation.user_id }}
    <br>
    店舗ID:
    {{ reservation.restaurant_id }}
    <p>
        <a href="{% url 'washoku:index' %}">top</a>
    </p>

{% endblock %}

Wafoods/reservation/templates/reservation/my_reserve.html
{% extends "base.html" %}

{% block title %}予約確認一覧 | {{ block.super }}{% endblock %}
{% block description %}予約確認一覧{% endblock %}

{% block content %}
<h1 id="ww">予約確認</h1>
now:
<span id="view_time"></span>

<table>
    {% for reserve in reservation %}
    {% if request.user.id == reserve.user_id %}
    <tr>
        <td>
        <textarea cols="30" rows="5" readonly>
名前: {{ reserve.name }}
日時: {{ reserve.datetime|date:"Y/m/j H:i" }}
人数: {{ reserve.number_of_people }}
        </textarea>
    </td>
    <td>
        <a href="{% url 'reservation:reserve_delete' reserve.id %}">cancel</a>
    </td>
    </tr>
    
    {% endif %}
    {% endfor %}
</table>


<script type="text/javascript">
document.getElementById("view_time").innerHTML = getNow();

function getNow() {
	var now = new Date();
	var year = now.getFullYear();
	var mon = now.getMonth()+1; //１を足すこと
	var day = now.getDate();
	var hour = now.getHours();
	var min = now.getMinutes();

	//出力用
	var s = year + "/" + mon  + "/" + day + " " + hour + ":" + min ; 
    return s;
}
</script>
{% endblock %}

Wafoods/reservation/templates/reservation/reserve.html
{% extends "base.html" %}

{% block title %}予約 | {{ block.super }}{% endblock %}
{% block description %}予約をするためのページです。{% endblock %}

{% block content %}
<h1 id="ww">予約</h1>
    {% if user.is_authenticated %}
    <table>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td>
                    <a class="zzz"><input id="btn" type="submit" value="予約"></a>
                </td>
            </tr>
        </form>
    </table>
    {% else %}
    <a href="{% url 'login' %}?next={{request.path}}">ログイン</a>されていません。
    {% endif %}
    <br>
    <a href="{% url 'washoku:index' %}">top</a>
{% endblock %}