Wafoods/Wafoods/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/',include('reservation.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('qee/', include("qee.urls")),
    path('', include('washoku.urls')),

]

Wafoods/qee/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'post/',views.post,name="post"),
    url(r'',views.index,name="index"),
    
]

Wafoods/washoku/urls.py
from django.urls import path
from django.conf.urls import url
from washoku import views
from washoku.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
)

app_name = 'washoku'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),

    
    path('create_restaurant/', views.create_restaurant, name='create_restaurant'),
    url(r'restaurant/([0-9]+)/',views.restaurantview,name='restaurant'),
    url(r'restaurant_en/([0-9]+)/',views.restaurantview_en,name='restaurant_en'),
    url(r'restaurant_list/delete/([0-9]+)',views.restaurant_delete,name='restaurant_delete'),
    url(r'restaurant_list/',views.RestaurantListView.as_view(),name='restaurant_list'),
    url(r'reserve_list/([0-9]+)',views.reserve_list,name="reserve_list"),
    
    url(r'calc_menu_en/([0-9]+)',views.calc_menu_en,name='calc_menu_en'),
    url(r'calc_menu/([0-9]+)',views.calc_menu,name='calc_menu'),
    

    url(r'make_menu/([0-9]+)',views.make_menu,name='make_menu'),
    url(r'menu/([0-9]+)/delete/',views.menu_delete,name='menu_delete'), 
    url(r'menu_en/([0-9]+)',views.menu_en,name='menu_en'),  
    url(r'menu/([0-9]+)',views.menu,name='menu'), 
    
    url(r'make_course/([0-9]+)',views.make_course,name='make_course'),
    url(r'course/([0-9]+)/delete/',views.course_delete,name='course_delete'),
    url(r'course_en/([0-9]+)',views.course_en,name='course_en'),  
    url(r'course/([0-9]+)',views.course,name='course'), 


    
    

]

Wafoods/washoku/forms.py
from django.forms import ModelForm, TextInput, Textarea

from django import forms

from washoku.models import Comment, Reply, Restaurant, Menu, Course

from cloudinary.forms import CloudinaryFileField #追加


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'コメント内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

class PhotoForm(forms.Form):
    image = forms.ImageField()

class RestaurantForm(forms.Form):
    name=forms.CharField()
    address=forms.CharField()
    detail=forms.CharField(widget=forms.Textarea)
    image = CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'Restaurant'})

class MenuForm(forms.Form):
    name=forms.CharField(label="メニュー名")
    price=forms.IntegerField(label="料金(税込)")
    description=forms.CharField(label="料理の説明",widget=forms.Textarea)
    image=CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'Menu'})

class CourseForm(forms.Form):
    name=forms.CharField(label="コース名")
    number_of_menus=forms.IntegerField(label="品目数")
    number_of_people=forms.CharField(label="人数")
    price=forms.IntegerField(label="料金(税込)")
    menus=forms.CharField(label="メニュー",widget=forms.Textarea)
    image = CloudinaryFileField(options={'folder': 'post_images/', 'tags': 'course'})

Wafoods/washoku/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from washoku.forms import CommentForm, ReplyForm, RestaurantForm, CourseForm, MenuForm
from washoku.models import Post, Category, Tag, Comment, Reply, Restaurant, Menu, Course
from reservation.models import Reserve

from googletrans import Translator


from PIL import Image
# Create your views here.

class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Restaurant
    template_name = 'washoku/index.html'
    paginate_by = 3


class CategoryPostView(ListView):
    model = Post
    template_name = 'washoku/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'washoku/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'washoku/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('washoku:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('washoku:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('washoku:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('washoku:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('washoku:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('washoku:post_detail', pk=reply.comment.post.pk)


#########

class MenuCourseListView(ListView):
    model = Menu
    context_object_name='menu'
    template_name='washoku/snippets/menu_course_list.html'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'courses' : Course.objects.all()
        })
        return context



def restaurantview(request,restaurant_id):
    if request.method == 'GET':
        return render(request, 'washoku/restaurant.html', {
            'menu' : Menu.objects.all(),
            'courses' : Course.objects.all(),
            'restaurant' : Restaurant.objects.get(pk=restaurant_id),
        })

def restaurantview_en(request,restaurant_id):
    if request.method == 'GET':
        return render(request, 'washoku/restaurant_en.html', {
            'menu' : Menu.objects.all(),
            'courses' : Course.objects.all(),
            'restaurant' : Restaurant.objects.get(pk=restaurant_id),
        })

def create_restaurant(request):
    if request.method=="GET":
        form=RestaurantForm()
        return render(request, 'washoku/create_restaurant.html', {'form':form})
    elif request.method=="POST":
        form = RestaurantForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()

        sent_detail_en=trans.translate(form.cleaned_data['detail'],dest="en").text

        restaurant = Restaurant()
        restaurant.name = form.cleaned_data['name']
        restaurant.address = form.cleaned_data['address']
        restaurant.detail = form.cleaned_data['detail']
        restaurant.detail_en = sent_detail_en
        restaurant.owner_id = request.user.id

        restaurant.image = form.cleaned_data['image']

        restaurant.save()
        return redirect("restaurant/"+str(restaurant.id))
    return render(request,'washoku/create_restaurant.html')

def restaurant_delete(request,rest_id):
    restaurant = Restaurant.objects.get(pk=rest_id)
    restaurant.delete()
    return redirect('/')


from .forms import PhotoForm
from .models import Photo


def photo(req):
    if req.method == 'GET':
        return render(req, 'washoku/create_restaurant.html', {
            'form': PhotoForm(),
            'photos': Photo.objects.all(),
        })

    elif req.method == 'POST':                                                     
        form = PhotoForm(req.POST, req.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        photo = Photo()
        photo.image = form.cleaned_data['image']
        photo.save()

        return redirect('/')

def make_menu(request,rest_id):
    
    if request.method == 'GET':
        form=MenuForm()
        return render(request, 'washoku/make_menu.html', {'form':form})

    if request.method=="POST":
        form = MenuForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()

        sent_name_en=trans.translate(form.cleaned_data['name'],dest="en").text
        sent_description_en=trans.translate(form.cleaned_data['description'],dest="en").text

        menu=Menu()
        menu.name=form.cleaned_data['name']
        menu.name_en=sent_name_en
        menu.price=form.cleaned_data['price']
        menu.description=form.cleaned_data['description']
        menu.description_en=sent_description_en
        menu.restaurant_id=rest_id

        menu.image = form.cleaned_data['image'] 
        menu.save()
        return redirect('restaurant/'+str(rest_id))

def menu(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    data={"menu":menu}
    return render(request,'washoku/menu.html',data)

def menu_en(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    data={"menu":menu}
    return render(request,'washoku/menu_en.html',data)

def menu_delete(request,menu_id):
    menu = Menu.objects.get(pk=menu_id)
    rest_id=menu.restaurant_id
    menu.delete()
    return redirect('/restaurant/'+str(rest_id))


def make_course(request,rest_id):
    if request.method == 'GET':
        form=CourseForm()
        return render(request, 'washoku/make_course.html', {'form':form})

    elif request.method == 'POST':                                                     
        form = CourseForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        trans=Translator()
        sent_name_en=trans.translate(form.cleaned_data['name'],dest="en").text
        sent_menus_en=trans.translate(form.cleaned_data['menus'],dest="en").text
        

        course = Course()
        course.name=form.cleaned_data['name']
        course.name_en=sent_name_en
        course.number_of_menus=form.cleaned_data['number_of_menus']
        course.number_of_people=form.cleaned_data['number_of_people']
        course.price=form.cleaned_data['price']
        course.menus=form.cleaned_data['menus']

Wafoods/washoku/templates/washoku/snippets/comments.html
{% for comment in post.comments.all %}
{% if user.is_authenticated or comment.approved %}
<div class="comment">
    <strong>{{ comment.author }}</strong>・{{ comment.timestamp }}
    <p>{{ comment.text|linebreaksbr }}</p>
    <p>
        <a href="{% url 'washoku:reply_form' comment.pk %}">返信する</a>
        {% if not comment.approved %}
        ｜<a class="text-success" href="{% url 'washoku:comment_approve' comment.pk %}">承認</a>
        ｜<a class="text-danger" href="{% url 'washoku:comment_remove' comment.pk %}">削除</a>
        {% endif %}
    </p>

    {% for reply in comment.replies.all %}
    {% if user.is_authenticated or reply.approved %}
    <div class="reply ml-5">
        <strong>{{ reply.author }}</strong>・{{ reply.timestamp }}
        <p>{{ reply.text|linebreaksbr }}</p>
        <p>
            {% if not reply.approved %}
            <a class="text-success" href="{% url 'washoku:reply_approve' reply.pk %}">承認</a>
            ｜<a class="text-danger" href="{% url 'washoku:reply_remove' reply.pk %}">削除</a>
            {% endif %}
        </p>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endfor %}

Wafoods/washoku/templates/washoku/snippets/main_post_list.html
{% for post in object_list %}
{% if user.is_authenticated or post.is_public %}

<div class="card mb-3">
    {% if post.image %}
    <a href="{% url 'washoku:post_detail' post.id %}">
        <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
    </a>
    {% endif %}
    <div class="card-body">
        {% if not post.is_public %}
        <h5><span class="badge badge-secondary">下書き</span></h5>
        {% endif %}
        <a href="{% url 'washoku:post_detail' post.id %}">
            <h5 class="card-title">{{ post.title }}</h5>
        </a>
        <p class="card-text">{{ post.published_at|date }}</p>
        <a href="{% url 'washoku:post_detail' post.id %}" class="btn btn-primary">記事を読む</a>
    </div>
</div>

{% endif %}
{% empty %}
<p>まだ投稿はありません。</p>
{% endfor %}

Wafoods/washoku/templates/washoku/snippets/menu_course_list.html
{% load cloudinary %}
<div class="tab_wrap">
        <input id="tab1" type="radio" name="tab_btn" checked>
        <input id="tab2" type="radio" name="tab_btn">
         
        <div class="tab_area">
            <label class="tab1_label" for="tab1">Menu</label>
            <label class="tab2_label" for="tab2">Course</label>
        </div>
        <div class="panel_area">
            <div id="panel1" class="tab_panel">
                <form name="menu">
                <table>
                    <tr>
                        <button><a class="zzz" href="{% url 'washoku:calc_menu' restaurant.id %}">料金計算</a></button>
                    </tr>
                    {% for m in menu %}
                    {% if m.restaurant_id == restaurant.id %}
                    <tr>
                        <td>
                            <a href="{% url 'washoku:menu' m.id %}">
                                {% cloudinary m.image.url width=100 height=100 %}
                                {{ m.name }}
                            </a>
                        </td>
                        <td>
                            <span name="price">{{ m.price }}</span>円
                        </td>
                        <td>
                            {% if request.user.id == restaurant.owner_id %}
                            <a href="{% url 'washoku:menu_delete' m.id %}">削除</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </table>
                </form>
            {% if request.user.id == restaurant.owner_id %}
            <a href="{% url 'washoku:make_menu' restaurant.id %}">メニュー追加</a>
            {% endif %}
            </div>
            <div id="panel2" class="tab_panel">
                <form name="course">
                    <table>
                        {% for course in courses %}
                        {% if course.restaurant_id == restaurant.id %}
                        <tr>
                            <td>
                                <a href="{% url 'washoku:course' course.id %}">
                                    {% cloudinary course.image.url width=100 height=100 %}
                                    {{ course.name }}
                                </a>
                            </td>
                            <td>
                                {{ course.price }}円
                            </td>
                            <td>
                                {% if request.user.id == restaurant.owner_id %}
                                <a href="{% url 'washoku:course_delete' course.id %}">削除</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </form>
                {% if request.user.id == restaurant.owner_id %}
                <a href="{% url 'washoku:make_course' restaurant.id %}">コース追加</a>
                {% endif %}
            </div>
        </div>
    </div>

Wafoods/washoku/templates/washoku/snippets/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation" class="aaa">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}"
                aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for num in paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <div class="page-link disabled">
                {{ num }}
                <span class="sr-only"></span>
            </div>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link ddd" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link ddd" href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}"
                aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

Wafoods/washoku/templates/washoku/snippets/search_form.html
<form class="form-inline my-2 my-lg-0" action="{% url 'washoku:search_post' %}" method="GET">
    <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search"
        aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
</form>

Wafoods/washoku/templates/washoku/snippets/sidebar.html
<div class="card mb-3">
    <div class="card-header">
        カテゴリ
    </div>
    <ul class="list-group list-group-flush">
        {% for category in categories|dictsort:"id" %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'washoku:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
            <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="card">
    <div class="card-header">
        タグ
    </div>
    <ul class="list-group list-group-flush">
        {% for tag in tags|dictsortreversed:"num_posts"|slice:":5" %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'washoku:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
            <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
        </li>
        {% endfor %}
    </ul>
    <div class="card-body text-center">
        <a href="{% url 'washoku:tag_list' %}" class="card-link">すべてのタグを見る</a>
    </div>
</div>